import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"; //dikasih @untuk mengarah ke root

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <h1 className="bg-red-800">HELLO FSW 1 DARI ROOT LAYOUT</h1>
      <Header />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
